#include "bldebug.h"
#include "builder.h"
#include "mir_printer.h"
#include "stb_ds.h"

static void print_header(const char *name, const char *filename, FILE *stream) {
	char date[26];
	date_time(date, 26, "%d-%m-%Y %H:%M:%S");

	fprintf(stream,
	        ";  Mid-level IR source file generated by blc.\n"
	        ";  Assembly:    %s\n"
	        ";  File:        %s\n"
	        ";  Created:     %s\n"
	        ";  BLC version: %s\n",
	        name,
	        filename,
	        date,
	        BL_VERSION);
}

void mir_writer_run(struct assembly *assembly) {
	str_buf_t export_file = get_tmp_str();

	const char          *name   = assembly->target->name;
	const struct target *target = assembly->target;

	str_buf_append_fmt(&export_file, "{str}/{s}.blm", target->out_dir, name);

	FILE *f = fopen(str_buf_to_c(export_file), "w");
	if (f == NULL) {
		builder_error("Cannot open file " STR_FMT, STR_ARG(export_file));
		put_tmp_str(export_file);
		return;
	}
	print_header(name, str_buf_to_c(export_file), f);
	mir_print_assembly(f, assembly);
	fclose(f);
	builder_info("Mir code written into " STR_FMT, STR_ARG(export_file));
	put_tmp_str(export_file);
}
